### ISSUE TITLE
Multiple Pages?

### ISSUE THREAD

**Issue by tbehrensprivate** [betatim/notebook-as-pdf#16]
Hello everyone,

notebook-as-pdf... I have been waiting for years for this functionality! Great work!

Would it be feasible to add a feature that allows for exporting multiple pages? 

Best,
Tristan

**Comment by betatim** [comment]
Right now notebook-as-pdf will make multiple pages if the resulting page ends up being too big (more than 200in which seems to be about the limit of Acrobat Reader). It doesn't create A4 (or similar) sized pages because a lot of people said "we don't really print the PDF, its just for sharing". This means the (very) large page(s) are a feature.

What kind of situation did you have in mind where having smaller pages would be good? What is the back story to the situation where you go "need this notebook as a PDF but heck not just one big page!". Having some details and context would help figure out what to do next.

**Comment by tbehrensprivate** [comment]
Hi Tim,

thanks for your reply! I am happy to tell you more.

You see, I teach a lot of Data Science and Deep Learning. I usually prepare several notebooks and keep them on my paper tablet (https://remarkable.com/). There it would make sense to have A4 pages.

Best,
Tristan
